#!/bin/bash
#
# chkconfig: 35 90 12 description: flamescp daemon
#
# Get function from functions library
. /etc/init.d/functions
# Start the service MAT
start() {
        nohup /usr/sbin/flamescpd &
        service httpd start &> /dev/null
        echo "flamescpd: Started daemon!"
}
# Restart the service MAT
stop() {
        pkill -9 flamescpd
        screen -S mcserver -X quit
        echo "flamescpd: Stopped daemon and killed any running minecraft servers."
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1 
        esac 
        exit 0 
