#!/bin/bash

echo "flamescpd: started"

# Remove pipe if it already exists

rm -rf /var/run/flamescp.sock

# Create pipe in /var/run/flamescp.sock
mkfifo /var/run/flamescp.sock
chmod 777 /var/run/flamescp.sock

while true; do

while read line; do
echo "[`date -u`] Received: ${line}" > /tmp/flamescp.log
echo "[`date -u`] Received: ${line}"

if [ "$line" == "start" ]; then
screen -dmS mcserver /scripts/start.sh
else if [ "$line" == "stop" ]; then
screen -dmS flamescpjob /scripts/stop.sh
else if [ "$line" == "reloadftp" ]; then
service vsftpd restart
else
/scripts/sendcmd.sh "$line"
fi
fi
fi


done</var/run/flamescp.sock

done

